### ISSUE TITLE
HomeHandler should not 'finish' in View and Stop but raise

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#106]
Let view and stop raise and then the HomeHandler.post will handle the logging.

https://github.com/simphony/simphony-remote/blob/98ee374756694ef1855a9d38d78d3561ec6cc54e/remoteappmanager/handlers/home_handler.py#L155

https://github.com/simphony/simphony-remote/blob/98ee374756694ef1855a9d38d78d3561ec6cc54e/remoteappmanager/handlers/home_handler.py#L132

**Comment by itziakos** [comment]
Yes, I think it makes sense to make this change. Thanks @kitchoi
