### ISSUE TITLE
REST: Expand protocol for enhanced REST

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#107]
The current REST protocol follows pristine REST. There is no support for arguments, or enhanced data  information when browsing the collection (only resource list) with the result that to inquire a collections' resources we need to issue one HTTP request per resource.

While this is not "pure REST" it's definitely useful in practice and not uncommon, so we should consider this addition and use it for our objective.

**Comment by itziakos** [comment]
This is a good point. I will expect to have a better idea on what is needed based on user feadback. For the moment we should be ok with the current implementation (even if it is a little slow).

**Comment by stefanoborini** [comment]
Closing after migration
