### ISSUE TITLE
REST: Extract REST framework in a separate package

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#108]
The REST framework can almost be separated into an independent package. I say almost because the biggest connection between REST and the application is the authentication, which is the reason why the REST BaseHandler inherits from our application BaseHandler: to get `prepare()` and have the user defined.

Once a solution for that is found, the REST becomes a reusable component.

**Comment by itziakos** [comment]
Lets use the framework for a while before we decide on factoring the generic library out.

**Comment by stefanoborini** [comment]
The package has been extracted in simphony/tornado-crud. We are still not dependent on it, because a release need to be done, and the authentication problem must be addressed.
