### ISSUE TITLE
Auditing of concurrency/race conditions problems

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#137]
It would be a good idea to do an overall auditing if concurrency problems may exist. Most of our interaction is readonly, the only "write" shared resource being the docker container manager, which is protected by a flag checking if a container start is already in progress.

Nevertheless, it's a good plan to squash these problems earlier.

**Comment by itziakos** [comment]
I would suggest to do this before 0.7.0 and any bug found are addressed on 0.8.0

**Comment by stefanoborini** [comment]
I'll do an overall investigation, and add issues as I find them.

**Comment by stefanoborini** [comment]
I am adding issues here

- One (potential?) in jupyterhub https://github.com/jupyterhub/jupyterhub/issues/721

**Comment by stefanoborini** [comment]
Too vague and mostly fixed by investigating the code as of version 1.1.0
