### ISSUE TITLE
Config file path for remoteappmanager can now be optional

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#138]
Since the default remoteappmanager config file is now basically empty, we might as well default it to None and not parse it altogether.  This would eliminate the need of creating an empty config file.

Enhancement for user experience

**Comment by kitchoi** [comment]
I have a branch for testing this behaviour so I could make a PR relatively quickly if this enhancement is accepted.

**Comment by stefanoborini** [comment]
@kitchoi do you still have the branch?

**Comment by kitchoi** [comment]
@stefanoborini Yes I still have it locally
