### ISSUE TITLE
Remove duplication between REST and home handler

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#140]
Now that container creation is performed by REST, there's a lot of duplication between the home handler and the REST api, notably in the POST strategy, the existence of support methods and so on.

Ideally, this duplication needs to be removed by issuing REST requests from a javascript operation directly to the REST api.

**Comment by stefanoborini** [comment]
On this regard, I am tempted to say that we need a supervisor object that manages the whole operation of starting and stopping a container. The container manager is, by design, focused _exclusively_ on docker, but starting a container for user consumption requires a few additional steps: setting up the reverse proxy, waiting for the service to be ready etc. Right now this logic resides in the controller class we have: the handler, but the handler is very web oriented.

I propose to:
- [ ] put most of the non-web logic in this separate "supervisor" object
- [ ] use the rest api to invoke its operations
- [ ] remove all logic from the home handler, especially the POST handler.
- [ ] leave home handler with a GET method returning a rendered template containing, in addition to the web page, a javascript rest client that can perform an authenticated rest request to our rest api, and change the buttons dynamically.

**Comment by stefanoborini** [comment]
I think we should use this one https://github.com/marmelab/restful.js

**Comment by stefanoborini** [comment]
Also this one https://www.npmjs.com/package/rest-js

**Comment by stefanoborini** [comment]
After much pain, I decided to give up on npm/browserify/rest-js. Too many issues. I'll try with bower and restful.js, and if that doesn't work either I'll just go jquery and suffer in silence.

**Comment by stefanoborini** [comment]
Giving up on bower and restful.js as well. It is unclear how bower creates the packages, and how we can integrate them in our js code. Requires webpack but generates a lot of errors due to missing packages (babel-core etc). Despite installing, could not reach a stable point.

Giving up. Going for the jquery approach.

**Comment by kitchoi** [comment]
Close via #165
