### ISSUE TITLE
Consider setting a default Accounting to something that always works

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#143]
Currently the default Accounting for `remoteappmanager` uses a sqlite3 database.  The Accounting would fail when the database is not setup.

This makes the application "not-work-out-of-the-box".

Potential default Accounting class may be one that returns all docker images in the host machine?  Or just an empty list of application?

**Comment by stefanoborini** [comment]
What we can do is to indeed have a "world accounting" that exports all images to all users, but it opens up one problem: distinguish images that are "valid" for us from images that aren't.

So we need to baptise a label to recognise an image as "one of us". Right now we don't really have such label, and taking advantage of any one of the currently present labels would be risky.

Any other strategy could open up to false positives (e.g. checking if only one port is exported, or if it derives from a specific base image)...

**Comment by kitchoi** [comment]
I personally prefer an empty list of applications then touching docker, higher chance of it to 'always work'

**Comment by itziakos** [comment]
I prefer that the spawner caprture's the error and shows the user an empty page with suggestions on how to fix the issue. ( e.g. link to the troubleshoting section in the docs)

**Comment by kitchoi** [comment]
Close via #159 and #160
