### ISSUE TITLE
Readthedocs build failures

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#157]
http://readthedocs.org/projects/simphony-remote/builds/4226458/

Error

Build environment creation failed

**Comment by itziakos** [comment]
It would be nice to sort it out for 0.6.0

**Comment by stefanoborini** [comment]
Reason being?

**Comment by stefanoborini** [comment]
I am a bit baffled by this one. I fixed yesterday the lack of astor by adding the doc-requirements in the readthedocs setup, but this was not the reason for the reported failure. Let's see what happens as we merge another PR. To me, it looks like a temporary failure due to rtd.

**Comment by kitchoi** [comment]
Fixed by wiping the cache on readthedocs.  Closing.
