### ISSUE TITLE
Exited container cannot be managed by the REST api

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#174]
Start a container that exits soon after (errors occur in the container for example), and then there is no way via the REST api to remove the zombie-like container.

Note:
1. RestResource.Container.create does not clean up if 'wait_for_container_ready' raises an Error
2. Other methods in RestResource.Container only care about *running* containers

**Comment by stefanoborini** [comment]
This is fixed in PR #186

**Comment by itziakos** [comment]
@kitchoi can this issue be closed?

**Comment by kitchoi** [comment]
Yes I think so.
