### ISSUE TITLE
Code audit: DOCKER_TLS_VERIFY

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#177]
https://github.com/simphony/simphony-remote/blob/master/remoteappmanager/file_config.py#L72 looks suspiciously wrong but it is actually consistent with docker.

From docker/docker#22411, tls_verify is False only by unsetting the environment variable DOCKER_TLS_VERIFY, i.e. 'DOCKER_TLS_VERIFY=0' still evaluate to `tls_verify = True`

Suggestion: add a comment there for future developers' reference

**Comment by itziakos** [comment]
:+1:
