### ISSUE TITLE
REST: Empty body responses should not have a content type set

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#184]
Responses having empty body should not define the content type. For similar discussion see

https://github.com/rack/rack/issues/472

this may seem trivial, but it emerged from an investigation on why jQuery considers 201 Created as an error status.

**Comment by stefanoborini** [comment]
Also see His Majesty (seriously) Jon Skeet response here http://stackoverflow.com/questions/15032932/what-should-the-content-type-be-for-a-4xx-error-without-a-body

**Comment by kitchoi** [comment]
Note that the RFC says there should be a Content-Type when there is a payload body (A -> B).  However it *does not* say that when there isn't a payload body, there shouldn't be a content-type (~B -> ~A).
Please also refer to this discussion: https://github.com/rack/rack/issues/787

**Comment by stefanoborini** [comment]
what should the content type be of no content?

**Comment by kitchoi** [comment]
That's another issue though?

**Comment by stefanoborini** [comment]
I am saying, after we found out what the RFC says or not says, what's the practical strategy to pursue, and if we have to have a Content-Type, what should the content type be if the response is 0 bytes?

**Comment by kitchoi** [comment]
> if we have to have a Content-Type, what should the content type be if the response is 0 bytes?
We don't have to have a Content-Type.  Rather, we don't forbid a content-type being defined unless the status code is one of (1xx, 204, 304)

**Comment by stefanoborini** [comment]
This is relative to REST responses, not a generic point over HTTP behavior. REST responses are responses that either have a payload (and this payload is generally encoded in some form, in our case json) or don't have a payload (and in this case the content type should not be defined).

**Comment by sjagoe** [comment]
What Content-Type generated the error in jquery?

I can see, for example, a Content-Type of application/json may be invalid for a zero-byte response. But text/plain may work fine; zero bytes of text is valid text.

**Comment by stefanoborini** [comment]
@sjagoe jQuery uses the content type to decode the payload, which is fine. However, when you get a 201, the payload is not an empty text document. It has no payload at all, and as such, no content type at all. 

I don't remember the exact jQuery problem that spawned this issue (IIRC, tornado was returning a json content type with a zero payload, and jQuery took that at face value and tried to jsondecode the payload, raising an exception).

My point is that there is a difference between the two, exactly like there's a difference between a python empty string and a python None. The first one can be encoded to utf-8, even if empty. The second one can't.

**Comment by sjagoe** [comment]
> It has no payload at all, and as such, no content type at all

This is in direct conflict with 

> tornado was returning a json content type with a zero payload

I was referring to the latter, i.e. the `Content-Type` header exists, with an `application/json` value. This is the scenario I would expect jquery to fail to decode. A zero byte payload is invalid JSON. 

However, if jquery is using the `Content-Type` header to decode, if you can override the content-type to be `text/plain`, zero bytes _is_ valid plain text. That would prevent jquery from doing _any_ decoding of the payload. No payload is a zero byte payload. That is a valid "payload" for an HTTP response.

**Comment by stefanoborini** [comment]
@sjagoe All of what you are saying is true. Using text/plain is possible (trivial) and would work, but it's a workaround due to how jquery "works". 

If you however take jquery quirks out of the equation, from the strictly formal point of view, I would expect no payload and empty text payload to have different characteristics in the content types. 

More on this topic:

http://stackoverflow.com/questions/21029351/what-content-type-should-a-204-no-response-use
https://github.com/hanami/controller/pull/62
https://java.net/jira/browse/JERSEY-953

All seem to indicate a general consensus that, including the RFC specifying that the presence of content-type is optional to begin with (meaning that no client must require it), there's no reason for content-type to be present in a 204 response.

**Comment by sjagoe** [comment]
> If you however take jquery quirks out of the equation, from the strictly formal point of view

Unfortunately, we're not living in a strictly formal and theoretical world. The web is broken, diverging from the "standards" in many places and we _have to_ use these kinds of workarounds. :-(

> Using text/plain is possible (trivial) 

Is it hard to make tornado not have return a `Content-Type` header at all? If not, you can try that. Otherwise you're stuck with sending a text/plain content type. Basically, I'm trying to answer this question:

> after we found out what the RFC says or not says, what's the practical strategy to pursue, and if we have to have a Content-Type, what should the content type be if the response is 0 bytes?

An alternative might be `Content-Type: application/octet-stream`, which is effectively explicitly telling the recipient "no encoding at all".

**Comment by stefanoborini** [comment]
@sjagoe 

> Is it hard to make tornado not have return a Content-Type header at all? 

Not at all. That's what I did. The problem (and the reason for the issue) is that there are other places in the code where an empty resource is returned where it still has a content type set. 

> Content-Type: application/octet-stream

I _think_ that a browser may decide to save it, but I am not sure. You are not supposed to interact with a browser anyway (well, not directly... only through ajax requests)

**Comment by stefanoborini** [comment]
Closing after migration
