### ISSUE TITLE
Unittesting of javascript code: add infrastructure

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#185]
As we use more and more javascript side code, we would like to unittest it as well.
At the moment we only perform end-user testing with selenium, but nothing is done at the unittest level.

**Comment by stefanoborini** [comment]
https://qunitjs.com/

The problem is that it is aimed at the browser so we need to pass through selenium. If we factor out non-DOM manipulation, then we can probably use node.js to run them, and leave dom manipulation to the browser. 

What about Rhino?

**Comment by itziakos** [comment]
It is something, that I have not done myself. In term of usability, I would like something that is easy to use and test on travis-ci.

**Comment by stefanoborini** [comment]
The PR adds just the infrastructure. Tests are missing (need to learn more about request and javascript) and will be added later.
