### ISSUE TITLE
REST: Allow for alternative encodes/decoders and representations.

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#188]
Currently we only handle json and dictionaries. It would be a nice addon to be able to plug encoders/decoders so we can support different representations.

Low priority for our purposes, but an important additional flexibility if we split the rest package out.

**Comment by itziakos** [comment]
I agree this issue should be part of the `rest` package when it is split-out and it is not directly necessary for simphony-remote

**Comment by stefanoborini** [comment]
Closing after migration
