### ISSUE TITLE
Home page of remoteappmanager does not require authentication

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#24]
Suppose a remoteappmanager is spawned for `user=username` and the reverse proxy is set for `/user/username`, anyone can access `https://hub_server_url/user/username` without logging in.

1. Log in as username
2. Open an incognito browser, go directly to https://hub_server_url/user/username

**Comment by kitchoi** [comment]
I am quite confident this is not intended and is a bug, but I want to confirm.

**Comment by stefanoborini** [comment]
The whole security of the mechanism has never been implemented. It's more than that. Please don't work on it. We are going to conflict.

**Comment by kitchoi** [comment]
Here is the fix (in a branch) for this issue: https://github.com/simphony/simphony-remote/tree/fix/home-requires-authentication
As you can see the changes are small.  Please let me know when I should create a PR for this change.
