### ISSUE TITLE
Give sensible name to home directories

### ISSUE THREAD

**Issue by dpinte** [simphony/simphony-remote#261]
The default location in `/tmp` is not desirable as it is not supposed to be persistant. The default location should be configurable (maybe it already is) and not in `/tmp`.

The names of the directories should be meaningful so that admins can do something with them (.e.g container name - user name).

**Comment by kitchoi** [comment]
For the default location in `/tmp`, you can change it in the jupyterhub_config file: https://github.com/simphony/simphony-remote/blob/master/jupyterhub/jupyterhub_config.py#L21
Documentation should be updated to reflect this (mention this as an alternative to `mkdir /tmp/remoteapp` in simphony-remote/doc/source/deployment.rst

As for the names of the directories containing some meaningful contents, it is indeed not supported.
