### ISSUE TITLE
New user will not have applications visible due to initial startup of the remoteappmanager

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#305]
To reproduce the bug:
- have a user who is not in the remoteappmanager db yet perform a login.
- add the user to remoteappmanager db.
- grant some applications to the user.

No matter how much the user refreshes, the applications will not appear.

The reason is the following: when the user first performs the login, the remoteappmanager authentication looks the user up in the database, does not find it, and therefore sets account to None.
This operation is never performed again, so the user remains None even if later on it is added to the database. The fact that remoteappmanager for that specific user will remain active even after logout means that at the moment the only way to get the applications to show is to kill the process or wait for its timeout.

We can't add the user in response to a missing user, because the database could be a csv file.

So the only possible option is to perform the lookup in the database at every new interaction, because also the opposite could happen (the user was there, but then it's removed and therefore it should be set to Null)

**Comment by kitchoi** [comment]
Could the `Stop My Server` button on /hub/home a solution for such scenario?  Because that would force the remoteappmanager to restart and therefore reload from the database.

**Comment by stefanoborini** [comment]
@kitchoi yes, but it's a bit of a bad user experience, and a bit unexpected.

**Comment by kitchoi** [comment]
Editting the database is an admin action, and restarting the remoteappmanager can be an admin action too.  If the remoteappmanager state can be restored properly for the user, the user may not notice a thing.  Just suggesting an alternative for consideration ;)

**Comment by kitchoi** [comment]
> restarting the remoteappmanager can be an admin action too.

Note: This is already implemented in jupterhub.

**Comment by stefanoborini** [comment]
@kitchoi it's beside the point. The first thing I thought after adding a user, granting him a few apps, reloading and seeing nothing is not "I need to restart the server that may or may not be already running". It's "there's a bug".

**Comment by kitchoi** [comment]
This issue refers new users, but you also raise another possible issue with modifying the available apps for the user.  orm supports real-time update for the list of apps, csv doesn't, and there is no guarantee that any implementation of the database interface (abstracted out) could support real-time update.  I think that is a separate issue now.

> "I need to restart the server that may or may not be already running"

Jupyterhub already has an admin page and an admin can see if a user's server is running and is able to restart it.

**Comment by stefanoborini** [comment]
> This issue refers new users, but you also raise another possible issue with modifying the available apps for the user. orm supports real-time update for the list of apps, csv doesn't

Yes it does. We have to reopen and reparse the file at every new request, which is of course a performance nightmare, and it could fail... so we just have to check the modification time first, and then reparse if that's the case, and if things go wrong, just set to None and keep going.

It's not a great solution, but if someone wants CSV, he's not looking for performance anyway.

**Comment by stefanoborini** [comment]
Fixed by docs. Closing
