### ISSUE TITLE
Async the hub call for user verification

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#37]
Currently, the hub is inquired synchronously for the user, meaning that we might get lag if the hub is unreachable. It's unlikely as a scenario, but we prefer to have everything asynchronous.

**Comment by kitchoi** [comment]
As long as we need to authenticate using the cookie for tornado's handler's `current_user` (which is a property), we cannot `yield` and the `get_current_user` method cannot be a coroutine.  Alternatively we can ease traffic by caching previously authenticated cookies and do less of `verify_token`

**Comment by stefanoborini** [comment]
@kitchoi 
```
        * It may be set as a normal variable, typically from an overridden
          `prepare()`::
              @gen.coroutine
              def prepare(self):
                  user_id_cookie = self.get_secure_cookie("user_id")
                  if user_id_cookie:
                      self.current_user = yield load_user(user_id_cookie)
        Note that `prepare()` may be a coroutine while `get_current_user()`
        may not, so the latter form is necessary if loading the user requires
        asynchronous operations.
```

**Comment by stefanoborini** [comment]
We just need to override prepare
