### ISSUE TITLE
Switch from old javascript to new javascript

### ISSUE THREAD

**Issue by martinRenou** [simphony/simphony-remote#382]
We should maybe switch from old javascript to new javascript. See http://es6-features.org/.

- [x] var -> let
- [x] old class definition -> new class definition http://es6-features.org/#ClassDefinition

**Comment by stefanoborini** [comment]
What's the support of ECMA 6 for all browsers we support?

**Comment by martinRenou** [comment]
If I'm correct, using babelify will assure support with all browsers
