### ISSUE TITLE
Attach workspace to virtual users

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-remote#4]
The task involves the following:

- hub server starts as hub-server
- Authentication is custom
- Single user manager app starts as hub-server
- The single user manager creates if necessary a dedicated folder for a new user.
- The single user manager attaches the dedicated folder to the new container as /worspace
- Provide support for upload/download of the files in the workspace (probably at the level of the single user manager).

**Comment by kitchoi** [comment]
Just wanted to clarify, the hub server may or may not be run as root?

**Comment by itziakos** [comment]
Yes, this setup should not require the Jupyter Hub server to be started as root.

**Comment by itziakos** [comment]
please note that 
> Provide support for upload/download of the files in the workspace (probably at the level of the single user manager).

if #9 which is designated for milestone 0.4.0

**Comment by kitchoi** [comment]
@itziakos Thanks!  I did not notice that #9 is in 0.4.0...

**Comment by stefanoborini** [comment]
@kitchoi What's the status of this one? Finished or there's still work to do? should it be moved to 0.4.0?

**Comment by kitchoi** [comment]
@stefanoborini @itziakos The first 5 bullet points in this task is completed via #36.
The last bullet point regarding upload/download, as far as I understood, is in milestone 0.4.0, so I am not working on it at the moment.

**Comment by stefanoborini** [comment]
@kitchoi Ok, then I close this.
