### ISSUE TITLE
Viewing a started container does not work anymore

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#43]
Pressing the button "View" no longer brings you back to the started application novnc page.
```
[I 2016-07-04 09:37:06.106 JupyterHub log:100] 200 GET /hub/api/authorizations/cookie/jupyter-hub-token-kit/[secret] (kit@172.16.253.129) 11.74ms
[W 160704 09:37:06 home_handler:346] Server at http://0.0.0.0:32772/user/kit/containers// responded with: 404
```
This is because assignment of `url_id` is not added to `remoteappmanager.docker.container.Container.from_docker_dict`

**Comment by itziakos** [comment]
I think that this is a serious bug that needs to be addressed in 0.3.0
