### ISSUE TITLE
Synchronization issues with the server

### ISSUE THREAD

**Issue by martinRenou** [simphony/simphony-remote#475]
In the user's page, the application list is provided by the server at page loading. Once the page is loaded, we never do any other request to the server in order to know what is in the application list. So if an admin user adds a new application, or remove an application, it won't be updated on the user's page.

Currently, the only way for the user to synchronize the application list with the server is to refresh the page.

**Comment by stefanoborini** [comment]
Solving this is an even bigger can of worms than the REST+JSONAPI. Wontfix. The user must reload.
