### ISSUE TITLE
Consistency with url vs urlpath

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#54]
There's a general inconsistency in "url" vs "urlpath" that makes things harder to understand.

- a url is according to `scheme:[//[user:password@]host[:port]][/]path[?query][#fragment]`, meaning that `http://host:8000/foo/bar` is a url. `/foo/bar` is not.
- a urlpath is a path that goes into a url. We want this distinction because some paths are on the physical machine instead, so just saying path does not convey the appropriate context.

This inconsistency is inherited from jupyterhub, but now that we have control of the spawner and we pass what we want at the command line, we should be clear on the intent to avoid confusion.

**Comment by itziakos** [comment]
is this fixed now?

**Comment by stefanoborini** [comment]
@itziakos Partially, I fear. The merged solution fixes the option, but internally I am not sure we are consistent everywhere.

**Comment by kitchoi** [comment]
@sbo @itziakos shall we close this and open new issue when we spot missed loners?  I don't guarantee I cleaned up all of them, but I tried my best.

**Comment by itziakos** [comment]
Yes it is fine to open new issues on this
