### ISSUE TITLE
Constraint the remoteappdb application creator names

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#55]
RIght now, anything goes into the database, but our applications have a well defined name. We might even consider checking the name against the docker repo, and throw an error if the image is not available.

**Comment by stefanoborini** [comment]
Note that technically, we should still manage to skip those images that are not present but are marked in the database (as we are doing now) in the web application, because one could remove the image from the docker machine and not update the database. We want however to make it harder to put an incorrectly typed name to begin with, when registering a new application.

**Comment by itziakos** [comment]
I would expect that the responsibility of keeping the database in sync with the docker available images is part of the IT maitenance. I am happy to provide offline (i.e. cli tools) that could verify the integrity and detect problems. However, the web application should not try to be proactive on this. Just report the issue in the logs and continue.

**Comment by stefanoborini** [comment]
@itziakos This is technically implemented in the --verify option. it's already merged.

**Comment by kitchoi** [comment]
@itziakos https://github.com/simphony/simphony-remote/issues/58 is for verifying the docker image name at the time of adding a row in the database.  However this issue also refers to the continuous consistency of the database and the docker machine.
