### ISSUE TITLE
React when containers fail to start

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-remote#6]
This items involves the following

- detection of the failure
- reaction (UI)

**notes**:
- The design in the images from simphony-remote-docker is such that users can contribute their own images that would work with the remote app framework. That said, it is possible for an unaware user to overwrite the default ENTRYPOINT. For example, ENTRYPOINT ['sleep', '1000'] would lead to a container up and running (for 1000 sec) with a live ip and port. We may enforce the entrypoint from the docker client.
-  One way to check if the container indeed has noVNC up and running would be to do docker.top(container_name) and look for 'x11vnc' or 'websockify' ( or 'openbox-autostart'?)

**Comment by kitchoi** [comment]
Close via #21
