### ISSUE TITLE
verify_token should return True or False, not raise HTTPError

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#62]
The signature of Hub.verify_token is a bit inconsistent. I suspect we use it for returning a reason for the failure, but it just looks weird, it might need some thought.

**Comment by kitchoi** [comment]
In jupyterhub, it is okay to raise HTTPError because their BaseHandler has overwritten the `write_error` and render an error page with the HTTPError messages.  We could do the same with `write_error`.
As for successful request, it should return the json data instead.
