### ISSUE TITLE
Formalise error handling with the logger and the refnumber for the issue

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#73]
Currently when an error takes place in a number of places we generate a `refnumber` that can be displayed in the user when an error takes place. This `refnumber` is at the same time logged next to the related error. This will help to pinpoint the place in the logs where a specific error (reported by a user) took place and simplify debugging.

To achieve this I would suggest one of the following:

- Wrap the python `Logger`  logging functions so that they generate a refnumber, pass it to the logger and then return it to the caller.
- Provide a generic `log(self, level, msg, *args, **kwargs)` function in the `BaseHandler` that will generate the refnumber pass it to a python logger and return it.

I think that the second implementation is simpler and easier to test.

**Comment by itziakos** [comment]
@stefanoborini and @kitchoi  I have updated the description
