### ISSUE TITLE
Docker environment variables can be used as default docker client settings

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#85]
A number of environment variables are *already* available in the docker machine, including TLS settings.  Instead of requiring the remoteappmanager config file to provide *all* parameters for the docker client, we should use the environment variables when parameters are not specified in the config file.

For example, the remoteappmanager file config can provide just
```
tls_verify = ...
```
and this would override the environment variables `$DOCKER_TLS_VERIFY` while the other parameters would have default settings such as `tls_cert = $DOCKER_CERT_PATH/cert.pem` (`docker.from_env` can handle this path construction for you).

Note on implementation details: ContainerManager is configured by DockerClientConfig configurated by the config file.  If DockerClientConfig is not given, environment variables are used.  But we always provide such DockerClientConfig so the config file is always used.

Reference:
https://docs.docker.com/engine/security/https/#/secure-by-default
https://books.google.co.uk/books?id=C8XeCgAAQBAJ&pg=PA125&lpg=PA125&dq=kwargs_from_env+docker+py&source=bl&ots=pTVPUI769C&sig=rg7MkbDBZGnPvBNBFwVbszmRuf4&hl=en&sa=X&ved=0ahUKEwjj8prZv-3NAhXlIsAKHaRbAhMQ6AEIMDAD#v=onepage&q=kwargs_from_env%20docker%20py&f=false

**Comment by itziakos** [comment]
I think that it is possible to simplify 
```
if _platform == 'Darwin':
    # For platforms that have a separate docker machine, we need to connect
    # using tls, but if we use self-signed certificates, using tls as True
    # will produce an error of incorrect CA validation.
    # As a consequence, we set tls to false, and tls_verify to true, honoring
    # docker documentation (although not very clear on this point)
    # See https://docs.docker.com/engine/security/https/
    if "DOCKER_CERT_PATH" not in os.environ:
        raise ValueError("Docker environment has not been defined.")

    tls = False
    tls_verify = bool(int(os.path.expandvars("${DOCKER_TLS_VERIFY}")))
    tls_ca = os.path.expandvars('${DOCKER_CERT_PATH}/ca.pem')
    tls_cert = os.path.expandvars('${DOCKER_CERT_PATH}/cert.pem')
    tls_key = os.path.expandvars('${DOCKER_CERT_PATH}/key.pem')
    docker_host = os.path.expandvars("${DOCKER_HOST}")
elif _platform == 'Linux':
    # Linux works through unix socket, so we don't need tls.
    tls = False
else:
    raise RuntimeError("Unknown platform {}".format(_platform))
```

So something like the following 

```
tls =False
# Provide the path to the docker host default is to use the DOCKER_HOST environment variable if it exists.
#docker_host = 
```

And then in the ConfigFile object provide default values for the tls data based on the info returned by the docker client.

This should remove the checks on the platform and be more generic correct?

**Comment by kitchoi** [comment]
Yes this makes sense.  Thanks @itziakos

**Comment by stefanoborini** [comment]
I thought about it a bit, and this requires a non-trivial, but still simple cleanup.

steps are:

- I'll make the DockerClientConfig able to extract the information from the environment variables.
- in Application, a DockerClientConfig will be instantiated.
- variables that are defined in the file will overwrite this objects' content
- the config will be passed to the container manager, and that to AsyncDockerClient. As a result, AsyncDockerClient will accept the config mandatorily (used to do it optionally, with fallbacks as a consequence). We can eventually bring the optionality back, but we never have this use case.

**Comment by itziakos** [comment]
If I am correct the only change that needs to happen is in FileConfig where the tls related code needs to have default values.

**Comment by itziakos** [comment]
To clarify:

- FileConfig sets default values for the tls related attributes if they are not defined in the file
- DockerClientConfig is initialized in the Application with the necessary data from FileConfig
- AsyncDockerClient should be initialized with proper information and should not try to fallback (as uggested in https://github.com/simphony/simphony-remote/issues/85#issuecomment-233367432)

**Comment by stefanoborini** [comment]
@itziakos: yes, but that makes a lot of code quite redundant. Lack of values is already checked along the way...

plus, I realised that, apart from validation of type, DockerClientConfig is a bit uncalled for. It was implemented as part of the migration from the prototype (where we didn't have the async client, IIRC). The point is that there's no reason why the asyncdocker client should have a different configuration from the non-async version. At that point, the responsibility for the creation of the configuration (now a plain dictionary, which is what docker client accepts) moves to the application.

Which means that the application would:

- create the docker Client configuration dictionary (the dockerpy one) with kwargs_from_env()
- check if any values are actually defined in the file configuration, and replace the corresponding values in the dict as from above.
- pass this dictionary to the container manager, which basically uses it for the async docker client.

**Comment by itziakos** [comment]
> •create the docker Client configuration dictionary (the dockerpy one) with kwargs_from_env()

Is there a reason why this cannot happen in `ConfigFile` ?

**Comment by stefanoborini** [comment]
@itziakos two reasons.

1. I want to keep the ConfigFile class as a simple container that maps from the tornado options. It's just a data bag with no logic, and it has no "smart behavior" in itself.
2. The docker configuration is a set of keyword arguments, some of which refer to docker py objects. I don't want to have to import docker in the configuration file

**Comment by stefanoborini** [comment]
@itziakos I thought about it more. You might have a point. The thing that restrains me is that I assume that the configuration classes are the unadulterated content of the config file. If I release this restriction, then it becomes technically easier: I set the defaults for the traits, and remove the logic that "recovers" from missing options here and there. 

I still have to validate for reasonable data though (e.g. empty strings passed)

**Comment by itziakos** [comment]
> The thing that restrains me is that I assume that the configuration classes are the unadulterated content of the config file, If I release this restriction, then it becomes technically easier:

Yes, `ConfigFile` is an unfortunate name. In reality is it a configuration container that it initialized from a variety of sources (including a file). Having the logic there instead of the Application make the code cleaner and testing easier. You do not have to instantiate the application to test what configuration options are used. 

> I set the defaults for the traits, and remove the logic that "recovers" from missing options here and there. 

Yes, deciding on the options values early and upfront is big a plus in testing and debugging. Then there is not need for additional logic in the functional components for missing or bad options.

**Comment by stefanoborini** [comment]
@itziakos makes sense. Going for it. I think we should eventually change that name (it becomes confusing) but for now I'll leave it as such
