### ISSUE TITLE
Data import/export functionality for virtual users

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-remote#9]
We want the user to be able to import data to a container or disk space, and vice-versa retrieve data from a container. An appropriate web UI should allow to select a file or files from the local disk and send it to the running container (and vice-versa)

**note**: this related to task #4 since normal users should have alternative ways for download/upload

**Comment by itziakos** [comment]
This is a big issue and one that I would happily put out of scope. However, it is going to be a big part of the UX if we can at least investigate ways of setting something up. I do not necessary expect that it has to be implemented in the application. It could be something based on sft access to authenticated users.

**Comment by stefanoborini** [comment]
@itziakos @kitchoi considering we are almost done for 0.5.0 I'd say it's time to study a strategy for this.

**Comment by itziakos** [comment]
lets discuss the options on Friday and we can update the issue as necessary.

**Comment by stefanoborini** [comment]
Ok, I did some research, and I write here the notes of what I find.

Option 1: we use the remoteappdb, add a new handler, decorate it with tornado.web.stream_request_body(cls), and store the file in the right place.
Option 2: We use nginx upload module

1 requires to write the handler, which should be trivial, and handle all the io. It does not introduce problems with memory (it's a stream) nor of asynchronicity (data_received can yield and is called every time there's something)
2 requires we put a nginx that can authenticate against jupyterhub, and knows where to save the file, in front of the whole application.

Neither of these options introduce a "browsing mechanism" for our files.

**Comment by stefanoborini** [comment]
To browse, we could use https://pypi.python.org/pypi/browsepy/0.4.0 but this is a flask application that opens a separate port. This would require some changes on our end: the spawner would have to handle two processes, and consequently to add two addresses to the reverse proxy. This will cut the number of active users to half of what we have right now (which is constrained by available ports).

**Comment by stefanoborini** [comment]
The alternative is that we reuse it as a library, create a handler for it, and serve it from our own application.

**Comment by stefanoborini** [comment]
this is also worth exploring. Seems to provide both upload and download. Built on tornado. https://github.com/nbarrientos/uploadr

There's no deployed example though... we might have to test it ourselves.

**Comment by stefanoborini** [comment]
Two options: 

- have two applications or
- embed one in the other

**Comment by itziakos** [comment]
After off-line discussion the prevailing idea is have a special docker image that will run browserpy for each user.

**Comment by stefanoborini** [comment]
After I developed an initial infrastructure to do what we need, and played with browsepy a bit within its context, I found out that it's not really made for URL relocation.

I spoke with Simon and apparently there's no quick fix. I'll investigate further, but I suspect that either we have to hack considerably browsepy, or switch altogether.

**Comment by stefanoborini** [comment]
Attempting to use a different solution after discovering plenty of shortcomings in the browsepy code. Currently I have a file manager based on angular (https://github.com/joni2back/angular-filemanager) which seem much better both visually and in terms of user experience, however it is proving challenging due to the use of php. I seem to have reached a working solution, with the exception of the starting path. As soon as it's fixed, I'll abandon the browsepy approach altogether.

**Comment by stefanoborini** [comment]
Closing this one as we now have a decent, working client in the filemanager image
