### ISSUE TITLE
FileConfig's traits' help messages are not used in the documentation

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#92]
In the documentation, http://simphony-remote.readthedocs.io/en/latest/api/remoteappmanager.html#module-remoteappmanager.file_config
```
tls
A boolean (True, False) trait.

tls_ca
A trait for unicode strings.
```
etc.

They should be
```
tls
A boolean (True, False) trait.  If True, connect to docker with --tls

tls_ca
A trait for unicode strings.  Path to CA certificate for docker TLS
```
etc.

**Comment by itziakos** [comment]
``traits`` had the same, this will require a trailets aware sphinx extension (similar to https://github.com/enthought/trait-documenter)
