### ISSUE TITLE
Reconsider use of code 422 for UnprocessableEntity error in REST api 

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#97]
Code 422 is a webdav extension. It was recommended practice from the source I've seen
 
http://www.restpatterns.org/HTTP_Status_Codes/422_-_Unprocessable_Entity

but I am not sure it's the right choice.

**Comment by itziakos** [comment]
I assign this to me.

**Comment by stefanoborini** [comment]
@itziakos are you working on it or should I switch it to me?

**Comment by itziakos** [comment]
I was planning to ask around and work on this, but if you already know what to do please go ahead

**Comment by stefanoborini** [comment]
Ok. I think the best option that is also not a webdav extension is a plain and simple 400 bad request.
